companies/urls.py
from django.urls import path
from companies import views

app_name = 'company'

urlpatterns = [
    path('', views.CompaniesIndex.as_view(), name='index'),
    # path('read/<int:pk>/', views.ReadIndex.as_view(), name='read'),
    path('delete/<int:pk>/', views.DeleteCompanyView.as_view(), name='remove_company'),
    path('update/<int:pk>/', views.UpdateCompanyView.as_view(), name='update_company'),
    path('add/', views.CreateCompanyView.as_view(), name='create_company'),
    ]

jobs/urls.py
from django.urls import path

from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('', views.JobsIndex.as_view(), name='index'),
    #  path('read/<int:pk>/', views.ReadIndex.as_view(), name='read'),
    path('delete/<int:pk>/', views.DeleteJobsView.as_view(), name='remove_job'),
    path('update/<int:pk>/', views.UpdateJobsView.as_view(), name='update_job'),
    path('add/', views.CreateJobsView.as_view(), name='create_jobs')
    ]

numeProiect/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('numeAplicatie.urls')),
    path('companies/', include('companies.urls')),
    path('jobs/', include('jobs.urls')),
]

companies/models.py
from django.db import models

from numeAplicatie.models import Location


class Companies(models.Model):
    name = models.CharField('Company Name', max_length=200)
    website = models.CharField('Website', max_length=200)
    location = models.ForeignKey(Location, on_delete=models.ForeignKey)

    def __str__(self):
        return '{}-{}'.format(str(self.name), str(self.website))

companies/forms.py
from django import forms
from django.forms import TextInput, Select

from companies.models import Companies


class CompaniesForm(forms.ModelForm):
    class Meta:
        model = Companies
        fields = ['name', 'website', 'location']

        widgets = {
            'name': TextInput(attrs={'placeholder': 'Name of company', 'class': 'form-control'}),
            'website': TextInput(attrs={'placeholder': 'Website of company', 'class': 'form-control'}),
            'location': Select(attrs={'class': 'form-control'}),
        }

companies/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import ListView
from django.views.generic import UpdateView

from companies.forms import CompaniesForm
from companies.models import Companies


class CompaniesIndex(ListView):
    model = Companies
    context_object_name = 'all_companies'
    template_name = 'companies/companies_index.html'


class CreateCompanyView(CreateView):
    model = Companies
    template_name = 'companies/company_form.html'
    form_class = CompaniesForm

    def get_success_url(self):
        return reverse('company:index')


class UpdateCompanyView(UpdateView):
    model = Companies
    template_name = 'companies/company_form.html'
    form_class = CompaniesForm

    def get_success_url(self):
        return reverse('company:update_company', args=[self.object.id])


class DeleteCompanyView(DeleteView):
    model = Companies
    template_name = 'companies/company_form.html'
    form_class = CompaniesForm

    def get_success_url(self):
        return reverse('company:index')

templates/companies/companies_index.html
{% extends 'base.html' %}

{% block content %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <div><a class="btn btn-danger" href="{% url 'company:create_company' %}">Add company</a></div>

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Company Name</th>
            <th scope="col">Website</th>
            <th scope="col">Location</th>
            <th scope="col">ACTIONS</th>
        </tr>
        </thead>
        <tbody>
        {% if all_companies %}
            {% for x in all_companies %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ x.name|upper }}</td>
                    <td>{{ x.website|upper }}</td>
                    <td>Country {{ x.location.country }} - city {{ x.location.city }}</td>
                    <td><a class="btn btn-secondary" href="{% url 'company:update_company' x.id %}">EDIT</a>
                        <a class="btn btn-secondary" href="{% url 'company:remove_company' x.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        {% else %}
            <tr><td colspan="5" class="text-center">No data available</td></tr>
        {% endif %}
        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
{% endblock %}

templates/companies/company_form.html
{% extends 'base.html' %}
{% block content %}
     <form method="POST">
        {% csrf_token %}
         <div class="box">
            <div class="field">
                {% for field in form %}
                    <div class="form-control">{{ field.label }} {{ field }}
                    </div>
                    <div>{{ field.errors }}</div>
                {% endfor %}
            </div>
           <button type="submit" class="btn btn-info">Salveaza</button>
         </div>
     </form>
{% endblock %}