companies/urls.py
from django.urls import path
from companies import views

app_name = 'company'

urlpatterns = [
    path('', views.CompaniesIndex.as_view(), name='index'),
    # path('read/<int:pk>/', views.ReadIndex.as_view(), name='read'),
    path('delete/<int:pk>/', views.DeleteCompanyView.as_view(), name='remove_company'),
    path('update/<int:pk>/', views.UpdateCompanyView.as_view(), name='update_company'),
    path('add/', views.CreateCompanyView.as_view(), name='create_company'),
    ]

jobs/urls.py
from django.urls import path

from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('', views.JobsIndex.as_view(), name='index'),
    #  path('read/<int:pk>/', views.ReadIndex.as_view(), name='read'),
    path('delete/<int:pk>/', views.DeleteJobsView.as_view(), name='remove_job'),
    path('update/<int:pk>/', views.UpdateJobsView.as_view(), name='update_job'),
    path('add/', views.CreateJobsView.as_view(), name='create_jobs')
    ]

numeAplicatie/urls.py
from django.urls import path
from numeAplicatie import views

app_name = 'app1'

urlpatterns = [
    path('', views.HomeIndex.as_view(), name='home'),
    # path('read/<int:pk>/', views.ReadIndex.as_view(), name='read'),
    path('update/<int:pk>/', views.UpdateIndex.as_view(), name='update'),
    path('add_location/', views.CreateLocation.as_view(), name='add_new_location'),
    ]

numeProiect/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('numeAplicatie.urls')),
    path('companies/', include('companies.urls')),
    path('jobs/', include('jobs.urls')),
]

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
</head>

<body>
<section class="hero is-primary is-fullheight">

    <div class="navbar-end">
        <a href="#" class="navbar-item">
            Home
        </a>
        <a href="#" class="navbar-item">
            Profile
        </a>
        <a href="{% url 'jobs:index' %}" class="navbar-item">
            Jobs
        </a>
        <a href="{% url 'company:index' %}" class="navbar-item">
            Companies
        </a>
        <a href="{% url 'app1:home' %}" class="navbar-item">
            Location
        </a>
        <a href="#" class="navbar-item">
            Login
        </a>
        <a href="#" class="navbar-item">
            Sign Up
        </a>
        <a href="#" class="navbar-item">
            Logout
        </a>

    </div>
    <div class="hero-body">
        <div class="container has-text-centered">
            {% block content %}
            {% endblock %}
        </div>

    </div>
</section>
</body>

</html>

templates/location.html
{% extends "base.html" %}
{% block content %}

    <form method="POST">
        {% csrf_token %}
        <div class="box">
            <div class="field" style="background: red;">{{ error }}</div>
            <div class="field">

                {% for field in form %}
                    <div class="control">
                        {{ field.label }}
                        {{ field }}
                    {{ field.errors }}
                    </div>
                {% endfor %}

            </div>

            <button class="button is-block is-info is-large is-fullwidth">Salveaza</button>
        </div>
    </form>
{% endblock %}

templates/locations_edit.html
{% extends "base.html" %}
{% block content %}



{% endblock %}

templates/locations_index.html
{% extends 'base.html' %}
{% block content %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <div class="center"><a type="button" class="btn btn-secondary" href="{% url 'app1:add_new_location' %}">Add new location</a></div>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">CITY</th>
            <th scope="col">ACTIONS</th>
        </tr>
        </thead>
        <tbody>
        {% for x in all_locations %}
            <tr>
                <td scope="row">{{ forloop.counter }}</td>
                <td>{{ x.city|upper }}</td>
                <td><a class="btn btn-secondary" href="{% url 'app1:update' x.id %}">EDIT</a>
                <a class="btn btn-secondary" id="delete_{{ x.id }}">Delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/save_edit_locations.js"></script>
{% endblock %}