jobs/urls.py
from django.urls import path

from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('', views.JobsIndex.as_view(), name='index'),
    #  path('read/<int:pk>/', views.ReadIndex.as_view(), name='read'),
    path('delete/<int:pk>/', views.DeleteJobsView.as_view(), name='remove_job'),
    path('update/<int:pk>/', views.UpdateJobsView.as_view(), name='update_job'),
    path('add/', views.CreateJobsView.as_view(), name='create_jobs')
    ]

numeProiect/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('numeAplicatie.urls')),
    path('companies/', include('companies.urls')),
    path('jobs/', include('jobs.urls')),
]

jobs/models.py
from django.db import models

# Create your models here.
from companies.models import Companies


class Jobs(models.Model):
    type = models.CharField('Job type', max_length=200)
    url = models.CharField('Job url', max_length=200)
    title = models.CharField('Job title', max_length=200)
    description = models.TextField('Job description', max_length=200)
    how_to_apply = models.TextField('Job applying', max_length=200)
    company = models.ForeignKey(Companies, on_delete=models.ForeignKey)

jobs/forms.py
from django import forms
from django.forms import TextInput, Select

from jobs.models import Jobs


class JobsForm(forms.ModelForm):
    class Meta:
        model = Jobs
        fields = ['type', 'url', 'title', 'description', 'how_to_apply', 'company']

        widgets = {
            'type': TextInput(attrs={'placeholder': 'Type of job', 'class': 'form-control'}),
            'url': TextInput(attrs={'placeholder': 'URL', 'class': 'form-control'}),
            'title': TextInput(attrs={'placeholder': 'Title', 'class': 'form-control'}),
            'description': TextInput(attrs={'placeholder': 'Description', 'class': 'form-control'}),
            'how_to_apply': TextInput(attrs={'placeholder': 'How to apply', 'class': 'form-control'}),
            'company': Select(attrs={'class': 'form-control'})
        }

jobs/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from jobs.forms import JobsForm
from jobs.models import Jobs


class JobsIndex(ListView):
    model = Jobs
    context_object_name = 'all_jobs'
    template_name = 'jobs/jobs_index.html'


class CreateJobsView(CreateView):
    model = Jobs
    template_name = 'jobs/jobs_form.html'
    form_class = JobsForm

    def get_success_url(self):
        return reverse('jobs:index')


class UpdateJobsView(UpdateView):
    model = Jobs
    template_name = 'jobs/jobs_form.html'
    form_class = JobsForm

    def get_success_url(self):
        return reverse('jobs:update_job', args=[self.object.id])


class DeleteJobsView(DeleteView):
    model = Jobs
    template_name = 'jobs/jobs_form.html'
    form_class = JobsForm

    def get_success_url(self):
        return reverse('jobs:index')

templates/jobs/jobs_form.html
{% extends 'base.html' %}

{% block content %}
	<form method="POST">
		{% csrf_token %}
		<div class="box">
			<div class="field">
				{% for field in form %}
					<div class="form-control">{{ field.label }} {{ field }}
					</div>
					<div>{{ field.errors }}</div>
				{% endfor %}
			</div>
			<button type="submit" class="btn btn-info">Salveaza</button>
		</div>
	</form>

{% endblock %}

templates/jobs/jobs_index.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <div><a class="btn btn-danger" href="{% url 'jobs:create_jobs' %}">Add job</a></div>

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Type</th>
            <th scope="col">Url</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">How To Apply</th>
            <th scope="col">Company</th>
            <th scope="col">ACTIONS</th>
        </tr>
        </thead>
        <tbody>
        {% if all_jobs %}
            {% for x in all_jobs %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ x.type|upper }}</td>
                    <td>{{ x.url }}</td>
                    <td>{{ x.title }}</td>
	                <td>{{ x.description }}</td>
	                <td>{{ x.how_to_apply }}</td>
	                <td>{{ x.company.name }}</td>
                    <td><a class="btn btn-secondary" href="{% url 'jobs:update_job' x.id %}">EDIT</a>
                        <a class="btn btn-secondary" href="{% url 'jobs:remove_job' x.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        {% else %}
            <tr><td colspan="7" class="text-center">No data available</td></tr>
        {% endif %}
        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
{% endblock %}